# LOGIN: Use 'admin' and 'secretpassword' to enter the database.
# FLOW: This file sets up the DB, adds categories, and starts the server.
services:

  db:
    image: mongo:8.0
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
    volumes:
      - mongodb_data:/data/db


  web:
    build: .
    #Run custom migrations and seed data before launching the server
    command: >
      sh -c "python manage.py migrate_product_categories && 
             python manage.py seed_categories && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - MONGO_HOST=db 
      - MONGO_PORT=27017
      - MONGO_DB=product_db
      - MONGO_USER=admin
      - MONGO_PASSWORD=secretpassword
    depends_on:
      - db

volumes:
  mongodb_data: